gun:
  pistol:
    displayName: Pistol
    spread: 0.15
    scopedSpread: 0.05
    scopedZoom: 1
    attackSpeed: 3
    magazineSize: 10
    soundRange: 4
  ar:
    displayName: Assault Rifle
    spread: 0.15
    scopedSpread: 0.01
    scopedZoom: 3
    attackSpeed: 7
    magazineSize: 25
    soundRange: 10
  sniper:
    displayName: Sniper Rifle
    spread: 0.25
    scopedSpread: 0.001
    scopedZoom: 25
    attackSpeed: 0.5
    magazineSize: 5
    soundRange: 20